### ISSUE TITLE
pbp.df name

### ISSUE THREAD

**Issue by kcolombe** [kpelechrinis/NBA-ref-analysis#2]
Hello,

I think there was an issue in racial_bias.R with setting up pbp.df in that you first call it pbp and then reference pbp.df later on in the code.

Best,
kc

**Comment by kcolombe** [comment]
Code for reference:

**pbp** <- read.csv("pbp.csv")
technicals <- c("Hanging Technical","Taunting Technical","Technical","Unsportsmanlike Technical")
refs_race.df <- read.csv("refs.csv")
players_race.df <- read.csv("player_race2.csv")
pids.df <- read.csv("nba_playerIds.csv")
boxscores <- read.csv("boxscores.csv")
boxscores$MIN = gsub(":"," ",boxscores$MIN)
boxscores <- boxscores %>% separate(MIN, c('minutes', 'seconds'))
boxscores$toc = as.numeric(boxscores$minutes)+(as.numeric(boxscores$seconds)/60)
boxscores[boxscores$minutes=="",]$toc = 0
boxscore_merge = merge(boxscores,players_race.df[,c("PLAYER_NAME","Race")],by="PLAYER_NAME",all.x=TRUE)
tech.df = **pbp**[**pbp**$call_type %in% technicals,]

tech.df$ref_race = rep("",dim(tech.df)[1])
for (i in 1:dim(tech.df)[1]){
  if (tech.df[i,]$ref!=""){
    tech.df[i,]$ref_race = refs_race.df[refs_race.df$Ref==tech.df[i,]$ref,]$race
  }
}

pids.df$player_race = rep("",dim(pids.df)[1])
for (i in 1:dim(pids.df)[1]){
  tmp = players_race.df[players_race.df$PLAYER_NAME==pids.df[i,]$PLAYER_NAME,]
  if (dim(tmp)[1]>0){
    pids.df[i,]$player_race = tmp[1,]$Race
  }
}

tech.df$p_race = rep("",dim(tech.df)[1])

for (i in 1:dim(tech.df)[1]){
  if (dim(pids.df[pids.df$id==tech.df[i,]$pid,])[1]>0){
    tech.df[i,]$p_race = pids.df[pids.df$id==tech.df[i,]$pid,]$player_race
  }
}

games = unique(**pbp**$game_id)

games_added <- c()
for (g in 1:length(games)){
  gid = games[g]
  refs = unique(**pbp**[**pbp**$game_id==gid & **pbp**$ref!="",]$ref)
  if (length(refs)!=3){
    next
  }
  games_added <- append(games_added,gid)
}


wb_n = length(which(tech.df$ref_race == "white" & tech.df$p_race == "black" & tech.df$game_id %in% games_added))
ww_n = length(which(tech.df$ref_race == "white" & tech.df$p_race == "white" & tech.df$game_id %in% games_added))
bb_n = length(which(tech.df$ref_race=="black" & tech.df$p_race == "black" & tech.df$game_id %in% games_added))
bw_n = length(which(tech.df$ref_race=="black" & tech.df$p_race == "white" & tech.df$game_id %in% games_added))

ww_min = 0
wb_min=0
bb_min=0
bw_min = 0
for (i in 1:dim(refs_race.df)[1]){
  games_f= unique(**pbp.df**[**pbp.df**$ref == refs_race.df[i,]$Ref & **pbp.df**$game_id %in% games_added,]$game_id)
  for (g in 1:length(games_f)){
    bgame = boxscore_merge[boxscore_merge$GAME_ID==games_f[g],]
    if (refs_race.df[i,]$race=="white"){
      ww_min = ww_min+sum(as.numeric(bgame[bgame$Race=="white",]$toc),na.rm=T)
      wb_min = wb_min +sum(as.numeric(bgame[bgame$Race=="black",]$toc),na.rm=T)
    }
    if (refs_race.df[i,]$race=="black"){
      bw_min = bw_min+sum(as.numeric(bgame[bgame$Race=="white",]$toc),na.rm=T)
      bb_min = bb_min +sum(as.numeric(bgame[bgame$Race=="black",]$toc),na.rm=T)
    }
  }
}

**Comment by kpelechrinis** [comment]
Thanks for catching this typo.
