### ISSUE TITLE
min vs mins

### ISSUE THREAD

**Issue by kcolombe** [kpelechrinis/NBA-ref-analysis#3]
Also think there could be a typo here?

ww_sim[b] = 48*ww_ns/ww_mins
wb_sim[b] = 48*wb_ns/wb_mins
bb_sim[b] = 48*bb_ns/bb_mins
bw_sim[b] = 48*bw_ns/bw_mins
same_sim[b] = 48*(bb_ns+ww_ns)/(bb_mins+ww_mins)
diff_sim[b] = 48*(bw_ns+wb_ns)/(bw_mins+wb_mins)

**Comment by kpelechrinis** [comment]
Another typo indeed! Fixed

**Comment by kpelechrinis** [comment]
Another typo indeed! Fixed
